import os
import re
from gemini_client import request_gemini_llm
from groq_client import request_groq_llm
from bedrock_client import request_bedrock_llm
from database_client import execute_sql_query, get_database_schema_metadata
from db_config import ACTIVE_DB_TYPE

def _get_schema_string() -> str:
    """
    Retrieves the database schema string.
    It first checks if 'database_schema.md' exists locally.
    If it does, it reads and returns its contents.
    If not, it queries the database directly using get_database_schema_metadata().
    """
    md_filename = "database_schema.md"
    
    if os.path.exists(md_filename):
        print(f"Reading database schema from local file: {md_filename}")
        try:
            with open(md_filename, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            print(f"Error reading {md_filename}: {e}. Falling back to live database query.")
    
    print("Fetching database schema directly from Database...")
    columns_info = get_database_schema_metadata()
    if not columns_info:
        return ""
        
    schema_dict = {}
    for row in columns_info:
        table = row['TABLE_NAME']
        col = row['COLUMN_NAME']
        col_type = row['COLUMN_TYPE']
        
        if table not in schema_dict:
            schema_dict[table] = []
        schema_dict[table].append(f"{col} ({col_type})")
        
    schema_lines = []
    for table, cols in schema_dict.items():
        schema_lines.append(f"Table: {table}")
        schema_lines.append(f"Columns: {', '.join(cols)}")
        schema_lines.append("")
        
    return "\n".join(schema_lines)

def _get_business_rules_string() -> str:
    """
    Reads the business rules from a local text file if it exists.
    """
    rules_filename = "business_rules.md"
    if os.path.exists(rules_filename):
        try:
            with open(rules_filename, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            print(f"Error reading {rules_filename}: {e}")
    return ""

def _clean_sql(generated_sql: str) -> str:
    """
    Cleans up the SQL generated by the LLM.
    Removes <think>...</think> blocks, markdown code blocks,
    and surrounding whitespace.
    """
    # Remove <think>...</think> tags and their contents (dotall makes . match newlines)
    generated_sql = re.sub(r'<think>.*?</think>', '', generated_sql, flags=re.DOTALL)
    
    generated_sql = generated_sql.strip()
    
    # Check for markdown code blocks
    if generated_sql.startswith("```sql"):
        generated_sql = generated_sql[6:]
    if generated_sql.startswith("```"):
        generated_sql = generated_sql[3:]
    if generated_sql.endswith("```"):
        generated_sql = generated_sql[:-3]

    return generated_sql.strip()

def generate_sql_from_text(text: str, previous_query: str = None, error_message: str = None, llm_provider: str = 'groq') -> str:
    print("1. Preparing database schema and business rules...")
    schema_string = _get_schema_string()
    business_rules_string = _get_business_rules_string()
    
    if not schema_string:
        print("Failed to retrieve database schema.")
        return ""
        
    rules_section = ""
    if business_rules_string:
        rules_section = f"""
### BUSINESS RULES & GOLDEN QUERIES
You MUST follow these rules and examples when generating the SQL query:
{business_rules_string}
"""
    
    print(f"\n2. Sending request to {llm_provider.capitalize()} LLM to generate SQL...")
    
    db_type = ACTIVE_DB_TYPE
    
    # Different models respond better to different prompt structures.
    if llm_provider.lower() == 'groq':
        # Instruction-based prompt for open models like Llama
        if previous_query and error_message:
             prompt = f"""### INSTRUCTIONS
You are an expert {db_type} database developer.
- You previously generated the query below, but it failed with an error.
- Please analyze the error and the schema to fix the query.
- Return ONLY the corrected, raw {db_type} query. Do not add any other text, explanations, or markdown.

### SCHEMA
{schema_string}
{rules_section}
### ORIGINAL QUESTION
{text}

### FAILED SQL QUERY
{previous_query}

### {db_type} ERROR
{error_message}

### CORRECTED SQL QUERY:
"""
        else:
            prompt = f"""### INSTRUCTIONS
You are an expert {db_type} database developer.
- Given a database schema and a user question, generate a single, valid {db_type} query.
- Return ONLY the raw SQL query. Do not add any other text, explanations, or markdown.

### SCHEMA
{schema_string}
{rules_section}
### QUESTION
{text}

### SQL QUERY:
"""
    else:
        # Conversational prompt for Gemini and Bedrock/Claude
        base_prompt = f"""
You are an expert {db_type} database developer.

Here is the schema for the database:
{schema_string}
{rules_section}
"""
        if previous_query and error_message:
            prompt = base_prompt + f"""
I previously asked you to write a {db_type} query to answer the following request: "{text}"
You provided this query:
{previous_query}

However, executing that query resulted in this error:
{error_message}

Based ONLY on the provided schema and rules, please fix the query and rewrite it so that it executes without errors.
Return strictly ONLY the raw {db_type} SQL query. Do not include markdown formatting (like ```sql), do not include any explanations or conversational text.
"""
        else:
            prompt = base_prompt + f"""
Based ONLY on this schema and rules, write a {db_type} query to answer the following request:
"{text}"

Return strictly ONLY the raw SQL query. Do not include markdown formatting (like ```sql), do not include any explanations or conversational text.
"""
    
    try:
        # Route to the appropriate LLM provider
        if llm_provider.lower() == 'groq':
            generated_sql = request_groq_llm(prompt)

        elif llm_provider.lower() == 'bedrock':
            generated_sql = request_bedrock_llm(prompt)
        else:
            # Default to Gemini
            generated_sql = request_gemini_llm(prompt)
        # print(_clean_sql(generated_sql))
        return _clean_sql(generated_sql)
        
    except Exception as e:
        print(f"Error calling {llm_provider.capitalize()}: {e}")
        return ""

def _execute_multiple_queries(sql_query: str):
    """
    Executes multiple SQL queries separated by a semicolon (;).
    Returns the results of ALL executed SELECT queries as a list of results.
    """
    queries = [q.strip() for q in sql_query.split(';') if q.strip()]
    all_results = []
    
    for q in queries:
        try:
             results = execute_sql_query(q)
             if results is not None:
                  all_results.extend(results)
        except Exception as e:
             print(f"Warning: sub-query execution failed: {e}")
             
    if len(all_results) > 0:
        return all_results
    return None

def split_queries_with_comments(sql_text: str):
    """
    Splits a large SQL text string into individual queries, attempting to 
    keep leading comments associated with their respective queries.
    Returns a list of tuples: (comment_or_default_text, query)
    """
    # Remove overall markdown blocks if present
    sql_text = _clean_sql(sql_text)
    
    queries_data = []
    
    # Split by semicolon
    raw_queries = sql_text.split(';')
    
    for i, raw_q in enumerate(raw_queries):
        if not raw_q.strip():
            continue
            
        # Extract comments
        comments = []
        sql_lines = []
        for line in raw_q.strip().split('\n'):
            line = line.strip()
            if line.startswith('--'):
                # Clean up the comment syntax
                comments.append(line[2:].strip())
            elif line:
                sql_lines.append(line)
                
        actual_query = " ".join(sql_lines).strip()
        if not actual_query:
            continue
            
        # Create the description text
        if comments:
            desc = " ".join(comments)
        else:
            desc = f"Generated Query {i+1}"
            
        queries_data.append((desc, actual_query))
        
    return queries_data

def generate_and_execute_sql(text: str, max_retries: int = 3, llm_provider: str = 'groq'):
    """
    Generates a SQL query from text and executes it.
    If execution fails, it retries up to `max_retries` times, passing the error back to the LLM.
    Returns a tuple of (sql_query, results).
    """
    print(f"Generating SQL for request: '{text}' using {llm_provider.capitalize()}")
    
    # Generate initial SQL
    sql_query = generate_sql_from_text(text, llm_provider=llm_provider)
    if not sql_query:
        print(f"\nFailed to generate a valid SQL query via {llm_provider.capitalize()}.")
        return None, None
        
    for attempt in range(max_retries):
        print(f"\n--- Attempt {attempt + 1}: Generated SQL Query ---")
        print(sql_query)
        print("-" * 27)
        
        print("\nExecuting query on database...")
        try:
            results = _execute_multiple_queries(sql_query)
            print("Execution successful.")
            return sql_query, results
            
        except Exception as e:
            error_message = str(e)
            print(f"\nExecution failed with error: {error_message}")
            
            if attempt < max_retries - 1:
                print(f"\nRetrying generation with error context (Attempt {attempt + 2}/{max_retries})...")
                sql_query = generate_sql_from_text(
                    text=text, 
                    previous_query=sql_query, 
                    error_message=error_message,
                    llm_provider=llm_provider
                )
                if not sql_query:
                     print("\nFailed to generate a retry SQL query.")
                     return None, None
            else:
                print(f"\nMax retries ({max_retries}) reached. Execution failed.")
                return sql_query, None
    
    return None, None
